spring:
  application:
    name: birthday-reminder
  datasource:
    url: jdbc:mysql://localhost:3306/birthday-reminder?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

# MyBatis??
mybatis:
  #mapper????
  mapper-locations: classpath:mapper/*.xml
  configuration:
    # ??MyBatis???????
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    # ??????????
    map-underscore-to-camel-case: true


birthday:
  jwt:
    secret-key: birthday
    ttl: 7200000
    token-name: authentication

  wechat:
    appid:
    secret:


